### ISSUE TITLE
DOC: bug in windows line `doc/examples/github-actions.yml`

### ISSUE THREAD

**Issue by aburrell** [coverallsapp/coverage-reporter#117]
### What was wrong?

Following this example will result in the Windows reports failing
```
Run curl -sL https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-windows.zip | zcat > ./coveralls.exe
InvalidOperation: D:\a\_temp\3862d081-6a06-42ea-a5e2-99028ad6949b.ps1:2
Line |
   2 |  … leases/latest/download/coveralls-windows.zip | zcat > ./coveralls.exe
     |                                                   ~~~~~~~~~~~~~~~~~~~~~~
     | Cannot run a document in the middle of a pipeline: C:\Program Files\Git\usr\bin\zcat.
Error: Process completed with exit code 1.
```

### Potential fix

Using the bash command on the README works.  Recommend updating the example yaml to include the line from the README.

**Comment by nhubbard** [comment]
I wrote my own PowerShell command to make it work correctly:

```yaml
# Other info removed for clarity
jobs:
  build:
    steps:
      - name: Report Coveralls (Windows)
        if: startsWith(runner.os, 'Windows')
        run: |
          Invoke-WebRequest -Uri "https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-windows.zip" -OutFile "coveralls-windows.zip"
          Add-Type -AssemblyName System.IO.Compression.FileSystem
          [System.IO.Compression.ZipFile]::ExtractToDirectory("coveralls-windows.zip", ".")
          Remove-Item "coveralls-windows.zip"
          Start-Process -FilePath ".\coveralls.exe" -ArgumentList "report build/reports/kover/report.xml" -NoNewWindow -Wait
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
```
