### ISSUE TITLE
Unable to upload report using coverage-reporter v0.6.10

### ISSUE THREAD

**Issue by pjhoberman** [coverallsapp/coverage-reporter#124]
### What was wrong?

I'm not able to upload the report using the 0.6.10 version that was just released.

### Logs

```
coveralls-linux.tar.gz: OK
Parsing args
Dry run - 0
Reporting coverage
+ ./coveralls report --debug
 
⠀⠀⠀⠀⠀⠀⣿
⠀⠀⠀⠀⠀⣼⣿⣧⠀⠀⠀⠀⠀⠀⠀ ⣠⣶⣾⣿⡇⢀⣴⣾⣿⣷⣆ ⣿⣿⠀⣰⣿⡟⢸⣿⣿⣿⡇ ⣿⣿⣿⣷⣦⠀⠀⢠⣿⣿⣿⠀⠀⣿⣿⠁⠀⣼⣿⡇⠀⢀⣴⣾⣿⡷
⠶⣶⣶⣶⣾⣿⣿⣿⣷⣶⣶⣶⠶  ⣸⣿⡟ ⠀⢠⣿⣿⠃⠈⣿⣿⠀⣿⣿⢠⣿⡿⠀⣿⣿⣧⣤⠀⢸⣿⡇⣠⣿⡿⠀⢠⣿⡟⣿⣿⠀⢸⣿⡿⠀⠀⣿⣿⠃⠀⢸⣿⣧⣄
⠀⠀⠙⢻⣿⣿⣿⣿⣿⡟⠋⠁⠀⠀ ⣿⣿⡇⠀ ⢸⣿⣿⠀⣸⣿⡟⠀⣿⣿⣾⡿⠁ ⣿⣿⠛⠛⠀⣿⣿⢿⣿⣏⠀⢀⣿⣿⣁⣿⣿⠀⣾⣿⡇⠀⢸⣿⡿⠀⠀⡀⠙⣿⣿⡆
⠀⠀⢠⣿⣿⣿⠿⣿⣿⣿⡄⠀⠀⠀ ⠙⢿⣿⣿⠇⠈⠿⣿⣿⡿⠋⠀⠀⢿⣿⡿⠁⠀⢸⣿⣿⣿⡇⢸⣿⣿⠀⣿⣿⣄⣾⣿⠛⠛⣿⣿⢠⣿⣿⣿ ⣼⣿⣿⣿ ⣿⣿⡿⠋⠀
⠀⢀⣾⠟⠋⠀⠀⠀⠙⠻⣷⡀⠀⠀
 
  v0.6.10

🔍 Detected coverage file: .coverage
⚠️  Detected coverage format: python, but error with coverage executable: --: 1: coverage: not found
⚠️ Coverage reporter does not yet know how to process this file: .coverage
⏱️ Report parsing: 00:00:00.052611493
🚨 Nothing to report

Exited with code exit status 1
```

Similar to https://github.com/coverallsapp/coverage-reporter/issues/119, but with the new version. This started happening for us yesterday (April 18, 2024).

**Comment by jan-janssen** [comment]
Can this be related to using `coverage -a` https://coverage.readthedocs.io/en/latest/cmd.html ? It seems like the repositories which combine coverage from multiple individual runs using the `append` option are the ones which can no longer be read by `coveralls`.

**Comment by jan-janssen** [comment]
One way to fix it is using `coverage xml` before calling the action. That solved the issue for me.

**Comment by pjhoberman** [comment]
This is how our circleci config looks relevant to tests:
```
      # Run tests
      - run:
          name: Run tests
          command: |
            echo "==========================================================="
            echo "Gather the unit test files."
            echo "-----------------------------------------------------------"
            TESTFILES=$(circleci tests glob "src/**/test_*.py")
            echo "Munge the test files into unique, sorted lines in a file."
            echo $TESTFILES | tr ' ' '\n' | sort | uniq > circleci_test_files.txt
            echo "-----------------------------------------------------------"
            echo "Ask CircleCI to split the tests by previous timings."
            echo "  (this is a feature of their parallelism tools)"
            TESTFILES=$(circleci tests split --split-by=timings circleci_test_files.txt)
            echo "Split test files:"
            echo $TESTFILES
            echo "-----------------------------------------------------------"
            echo "Make the test filenames Python modules to pass to the test runner."
            TEST_MODULES=$(echo $TESTFILES | sed "s+src/++g" | tr "/" "." | sed "s+\.py++g")
            echo "-----------------------------------------------------------"
            echo "Test the following modules:"
            echo $TEST_MODULES
            echo "-----------------------------------------------------------"
            python -m coverage run --source=src -m discovery.manage test --verbosity 2 $TEST_MODULES
            echo "-----------------------------------------------------------"

      - coveralls/upload:
          parallel: true
          flag_name: test1
          verbose: true

      # Run coverage report for Coveralls
      - run:
          name: Generate Coverage Report for Coveralls
          command: |
            python -m coverage lcov

      - store_test_results:
          path: coverage/results

  upload-coverage:
    executor: node/default
    steps:
      - coveralls/upload:
          parallel_finished: true
          carryforward: test1
```

**Comment by afinetooth** [comment]
@pjhoberman based on your config above, I sent you some workaround steps in our existing email thread.

Basically, the error you're getting is not related to the version of Coverage Reporter anymore (we believe that previous issue was fixed). Instead, Coverage Reporter is choking on your `.coverage` file, for two reasons:

1. **Because our (beta) `pytest-cov` parser has been having challenges with the fairly nonstandard `.coverage` file format**  - Rather than being a text file, the `.coverage` file is a SQLite3 database, and, as coverage.py seems to also be pushing some boundaries around future coverage types, it is both a difficult to parse format and changing over time. So, the current "canonical" approach (across several implementations we've seen) is to convert the `.coverage` file to (cobertura-format) XML using the `coverage xml` command (per the [README](https://coverage.readthedocs.io/en/latest/cmd.html#xml-reporting-coverage-xml))
2. **Because you did not specify a `format:` input option** - Without using this input option to specify which format of coverage report the Coverage Reporter should look for, it will look for, and try to parse, all coverage reports of any format it finds. This is a problem---or at least redundant---when you have the same report in two different formats in your environment, which you seem to (`.coevrage` and `lcov`). but in short, the way to avoid trying to parse the `.coverage` report is to specify `format: lcov` in your input options.

You can fix this in one step:

1. Add `format: lcov` to your input options, per the change below:

```
      - coveralls/upload:
          format: lcov
          parallel: true
          flag_name: test1
          verbose: true

      # Run coverage report for Coveralls
      - run:
          name: Generate Coverage Report for Coveralls
          command: |
            python -m coverage lcov

      - store_test_results:
          path: coverage/results

  upload-coverage:
    executor: node/default
    steps:
      - coveralls/upload:
          parallel_finished: true
          carryforward: test1
```

Or you can even take the more "canonical" approach and convert your `.coverage` file to (cobertura) XML, which seems to be the most reliable conversion.

That would take two steps, per these changes:

```
      - coveralls/upload:
          format: cobertura
          parallel: true
          flag_name: test1
          verbose: true

      # Run coverage report for Coveralls
      - run:
          name: Generate Coverage Report for Coveralls
          command: |
            python -m coverage xml

      - store_test_results:
          path: coverage/results

  upload-coverage:
    executor: node/default
    steps:
      - coveralls/upload:
          parallel_finished: true
          carryforward: test1
```

(Note that the `format:` for (cobertura) XML is `cobertura`, as opposed to `xml`.)

Hope that helps.

If that fixes your issue, feel free to close this issue since, as I say, it's not related to the version of Coverage Reporter, and we don't believe there are any issues with `0.6.10` (still the latest version).
