### ISSUE TITLE
JSON::SerializableError on version 0.4.1

### ISSUE THREAD

**Issue by samrjenkins** [coverallsapp/coverage-reporter#76]
### What was wrong?
We have started seeing a coveralls-related error consistently across all of our projects. No changes have been made from our end. The appearance of the errors started exactly at the time the new v0.4.1 was released.

We use the coveralls github action (https://github.com/coverallsapp/github-action) to report coverage to Coveralls from our Github workflows.

We upload parallel coverage reports with the following configuration:
```yml
      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        if: always()
        with:
          flag-name: run-${{ matrix.franchise }}
          parallel: true
```
and we finish our parallel coverage report with:
```yml
  coveralls_finish:
    needs: rspec
    runs-on: ubuntu-latest
    steps:
      - uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
```

This had been working well for us for a while. It has suddenly broken today exactly at the time v0.4.1 was released.

### Logs
Here is the error we are seeing in our Github actions log:
```
🔍 Detected coverage file: coverage/lcov.info
🔍 Detected coverage file: coverage/.resultset.json
#<JSON::SerializableError:Couldn't parse (Array(Int64 | Nil) | CoverageReporter::SimplecovParser::ComplexCoverage) from {"lines":[null,null,1,1,null,1,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,179,null,1,98,null,null,1,0,null,null]} at line 4, column 63
  parsing CoverageReporter::SimplecovParser::Report#coverage at line 3, column 5>
Error: Process completed with exit code 1.
```
